apiVersion: apps/v1 
kind: Deployment
metadata:
  name: oai-amf
  namespace: oai-cn5g
  labels:
    app: amf
spec:
  selector:
    matchLabels:
      app: amf
  template:
    metadata:
      labels:
        app: amf
    spec:
      nodeSelector:
        nodetype: server
      containers:
        - name: oai-amf
          image: oaisoftwarealliance/oai-amf:latest
          ports:
            - name: http1
              containerPort: 80
              protocol: TCP
            - name: http2
              containerPort: 8080
              protocol: TCP
            - name: ngap
              containerPort: 38412
              protocol: SCTP
          env:
            - name: TZ
              value: Europe/Paris
            - name: MCC
              value: "208"
            - name: MNC
              value: "95"
            - name: REGION_ID
              value: "128"
            - name: AMF_SET_ID
              value: "1"
            - name: SERVED_GUAMI_MNC_0
              value: "208"
            - name: SERVED_GUAMI_MCC_0
              value: "95"
            - name: SERVED_GUAMI_REGION_ID_0
              value: "128"
            - name: SERVED_GUAMI_AMF_SET_ID_0
              value: "1"
            - name: SERVED_GUAMI_MNC_1
              value: "460"
            - name: SERVED_GUAMI_MCC_1
              value: "11"
            - name: SERVED_GUAMI_REGION_ID_1
              value: "10"
            - name: SERVED_GUAMI_AMF_SET_ID_1
              value: "1"
            - name: PLMN_SUPPORT_MCC
              value: "208"
            - name: PLMN_SUPPORT_MNC
              value: "95"
            - name: PLMN_SUPPORT_TAC
              value: "0xa000"
            # Slice 0 (1, 0xFFFFFF)
            - name: SST_0
              value: "1"
            # At least one slice SHALL be defined.
            # All the others are optional
            # Slice 1 (1, 1)
            - name: SST_1
              value: "1"
            - name: SD_1
              value: "1"
            # Slice 2 (222, 123)
            - name: SST_2
              value: "222"
            - name: SD_2
              value: "123"
            - name: AMF_INTERFACE_NAME_FOR_NGAP
              value: eth0
            - name: AMF_INTERFACE_NAME_FOR_N11
              value: eth0
            # One single SMF instance
            - name: SMF_INSTANCE_ID_0
              value: "1"
            - name: SMF_FQDN_0
              value: smf.oai-cn5g.svc.cluster.local
            - name: SMF_IPV4_ADDR_0
              value: smf
            - name: SELECTED_0
              value: "true"
            - name: NF_REGISTRATION
              value: "yes"
            - name: USE_FQDN_DNS
              value: "yes"
            - name: SMF_SELECTION
              value: "yes"
            - name: EXTERNAL_AUSF
              value: "yes"
            - name: EXTERNAL_UDM
              value: "no"
            - name: EXTERNAL_NSSF
              value: "no"
            - name: NRF_IPV4_ADDRESS
              value: nrf
            - name: NRF_FQDN
              value: nrf.oai-cn5g.svc.cluster.local
            - name: AUSF_IPV4_ADDRESS
              value: ausf
            - name: AUSF_FQDN
              value: ausf.oai-cn5g.svc.cluster.local
            - name: UDM_IPV4_ADDRESS
              value: udm
            - name: UDM_FQDN
              value: udm.oai-cn5g.svc.cluster.local
            # changes for HTTP2
            - name: USE_HTTP2
              value: "yes"
            - name: NRF_PORT
              value: "8080"
            - name: AUSF_PORT
              value: "8080"
            - name: UDM_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: amf
  namespace: oai-cn5g
spec:
  selector:
    app: amf
  ports:
    - name: http1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: http2
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: ngap
      protocol: SCTP
      port: 38412
      targetPort: 38412
